package com.dascom.cloudprint.common;

public interface DataBaseConstant {
	
	String DATABASE_ERROR_CODE_2001="2001";
	String DATABASE_ERROR_MESSAGE_DATABASEISCLOSE = "数据库已关闭！";
	
	String DATABASE_ERROR_CODE_2002="2002";
	String DATABASE_ERROR_MESSAGE_DATABASEOUTTIME = "数据库连接超时！";
	
	String DATABASE_ERROR_CODE_2003="2003";
	String DATABASE_ERROR_MESSAGE_DATABASEFIELDERROR = "字段转换异常！";
	
	String DATABASE_ERROR_CODE_2004="2004";
	String DATABASE_ERROR_MESSAGE_DATABASEQUERYEOUTTIME = "数据库查询超时！";
	
	String DATABASE_ERROR_CODE_2005="2005";
	String DATABASE_ERROR_MESSAGE_DATABASERUNERROR = "数据库运行异常！";
}
